CREATE TABLE IF NOT EXISTS tickets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key_token VARCHAR(64) UNIQUE,
  type VARCHAR(64),
  username VARCHAR(255),
  ip_address VARCHAR(64),
  revision_link TEXT,
  reason TEXT,
  status VARCHAR(32) DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ticket_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ticket_id INTEGER,
  event_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  event_text TEXT,
  FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ip_blocks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ip_address VARCHAR(64) UNIQUE,
  blocked_by VARCHAR(255),
  reason TEXT,
  expires_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(255) UNIQUE,
  role VARCHAR(32) DEFAULT 'user',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
